### ISSUE TITLE
Vulcanization looses order in the generated javascript file

### ISSUE THREAD

**Issue by Petermo** [Polymer/vulcanize#148] opened 2015-04-02 10:30 UTC
Hi,

It seems that the vulcanization (when using csp and inline) process looses its order of javascript files.
For example, take a look at http://petermo.github.io/index.html which is generated from http://petermo.github.io/Imports.html
The latter works as expected but the first one doesn't. In the generated Vulcanized.js file there are some Polymer() calls before it is defined.
My expectation would be that when including polymer.js through the imports the generated javascript maintains that order.
Is this expected (thus my expectation is wrong), a bug or something else I'm doing wrong...

The version of vulcanize is 0.7.9 and is used within grunt. Is this enough or would any other information be required/welcome? Please let me know.

**Comment by kaldrenon** [comment] 2015-04-06 19:23
I have experienced this result as well; I am using `--inline` and `--strip`

It seems like https://github.com/Polymer/vulcanize/blob/master/lib/vulcan.js#L94-L114 should be the culprit, but a quick read of that code doesn't reveal to me why it would happen.

Could it be that `searchAll($, constants.JS_SRC).each` doesn't maintain the order of its results?

**Comment by chiefcll** [comment] 2015-04-07 12:21
So we had this same issue - and the root cause was some invalid HTML. We had one polymer file that had some rogue characters which threw off the order. At the start of a file we had:
```
cv  <link rel="import" href="../polymer/polymer.html">
```
Having invalid html throws off the parser and was causing our script tag to be out of place.

**Comment by chiefcll** [comment] 2015-04-07 12:24
Peter - try removing the closing / on your imports

**Comment by Petermo** [comment] 2015-04-07 12:54
@chiefcll That indeed seems to be the culprit. However, my code isn't invalid HTML.
Having it narrowed down a bit, I'm now thinking about creating a new issue that references http://www.w3.org/TR/html5/syntax.html#void-elements

**Closed** 2015-05-22 22:33 UTC
