### ISSUE TITLE
Breaks when there are scripts of type ld+json

### ISSUE THREAD

**Issue by tigerhawkvok** [Polymer/vulcanize#230] opened 2015-08-15 05:20 UTC
So, this Schema.org blob breaks the vulcanization:

```html
    <script type="application/ld+json">
      { "@context" : "http://schema.org",
      "@type" : "Organization",
      "name" : "SSAR North American Species Names Database",
      "url" : "https://ssarherps.org/cndb/",
      "logo" : "https://ssarherps.org/cndb/assets/favicon1024.png",
      "image" : "https://ssarherps.org/wp-content/uploads/2015/03/Pseudacris_crucifer-1425x460.jpg",
      "description" : "The Society for the Study of Amphibians and Reptiles's searchable database of North American reptiles and amphibians. Species accounts, photos, geolocation, and more."
      }
    </script>
```

It should make sure that <scripts> don't have a type that **isn't* "text/javascript" or blank.

**Comment by azakus** [comment] 2015-08-17 18:41
Vulcanize already checks the type of script: https://github.com/Polymer/vulcanize/blob/master/lib/matchers.js#L24-L33

I this is a duplicate of https://github.com/Polymer/hydrolysis/issues/152, which should be fixed in the next hydrolysis release.

**Closed by azakus** 2015-08-17 18:41 UTC

**Comment by azakus** [comment] 2015-08-17 18:42
@garlicnation: let's make another hydrolysis release soon :)
