### ISSUE TITLE
webserver root -p error when --inline-scripts or --inline-css

### ISSUE THREAD

**Issue by TimWillis** [Polymer/vulcanize#243] opened 2015-09-16 17:39 UTC
I use vulcanize  --strip-comments -p "../" layout/layout.html > build/layout.html  
with no errors, but when I use vulcanize  --strip-comments -p "../" layout/layout.html > build/layout.html  --inline-css --inline-scripts
I get wrong path errors for the scripts/css it is trying to inline.

**Comment by azakus** [comment] 2015-09-23 22:07
Duplicate of #244

**Closed by azakus** 2015-09-23 22:07 UTC
