### ISSUE TITLE
--strip-comments doesn't strip all comments

### ISSUE THREAD

**Issue by eximius313** [Polymer/vulcanize#292] opened 2016-01-09 15:22 UTC
it still leaves:
```
//this comment
```
And
```
/**
* this comment
*/
```

**Comment by garlicnation** [comment] 2016-03-02 19:51
`--strip-comments` is mislabeled and should be `--strip-html-comments`.

CSS and JS comments are ignored.

**Comment by garlicnation** [comment] 2016-03-02 20:11
duplicate of #270

**Closed by garlicnation** 2016-03-02 20:11 UTC
Labels: Priority: Low, Status: Available, Type: Enhancement
