### ISSUE TITLE
Polymer source custom-styles get overrided by dependancy custom-styles after vulcanize

### ISSUE THREAD

**Issue by ThilinaTCH** [Polymer/vulcanize#375] opened 2016-09-23 08:39 UTC
Hi All,

We have a custom-style which applies some root level styles. We are keeping this in a separate html. Following is a sample of it,
`<link rel="import" href="../bower_components/polymer/polymer.html">

<style is="custom-style">

```
:root {
    --primary-text-color: var(--light-theme-text-color);
    }
```

</style>`

Also there is a dependency with paper-styles which has same kind of custom style which set some of same styles we are using (for ex --primary-text-color)

After vulcanization happens (we use polymer-starter-kit 2 here), it's first append out source custom-style and then dependency custom-style where all out styles getting overrides.

Any help would be really appreciated...

**Comment by Bubbit** [comment] 2016-11-24 15:49
I also have this issue, with vulcanize 1.14.8 it works, it seems to be broken since 1.14.10, couldn't get 1.14.9 to run due to: Error: stream.push() after EOF on same code base (with polymer-build 0.4.1 & 0.5.0)

**Comment by hvdb** [comment] 2016-11-29 05:16
The problem lays in the vulcan.js -> flatten function.

The body of a document and the head are parsed/treated differently.
While this is not a problem with generic html in general it is for css styling ofc..


We (@Bubbit and I) found a workaround.
If you put the custom style in a html file and link that inside the page where you want to override the styles, the styles will be put in the correct order.

example:

black-theme.html
```html
<link rel="import" href="../paper-styles/default-theme.html">


<style>
//some style
</style>
```

Workaround: 
Put the <style></style> part inside a new html file : b-theme.html

and import that in black-theme.html
```html
<link rel="import" href="../paper-styles/default-theme.html">

<link rel="import" href="b-thtme.html">

```


We will do some more investigation to see how we can fix it.
But there is a lot changed in this part recently so it is hard to find a good solution which doesn't break the last changes (script order)

May it is not even that bad to have the style in a different HTML file?

**Comment by Bubbit** [comment] 2016-11-30 17:51
Isn't this a duplicate of #357 ?

**Comment by usergenic** [comment] 2016-12-09 01:08
Vulcanize 1.15.1 released.  Should fix this.

**Closed by usergenic** 2016-12-09 01:08 UTC
